name: fortran-src-balanced-allocs
version: 0.1.0
synopsis: TODO
description: Please see README.md.
extra-source-files:
- README.md
- CHANGELOG.md
#category: Data
#tested-with: GHC ==9.2.2
license: MIT
license-file: LICENSE

#github: raehik/strongweak
maintainer: Ben Orchard <thefirstmuffinman@gmail.com>
author: Ben Orchard

# raehik's extensions (GHC 9.2; last updated: 2022-10-09)
language: GHC2021
default-extensions:
# syntax that should be default
- LambdaCase
- NoStarIsType

## deriving-related
- DerivingVia # implies DerivingStrategies
- DeriveAnyClass

# features that should be default
- GADTs
- RoleAnnotations

# other features
- DefaultSignatures
- TypeFamilies
- DataKinds

# other syntax
- MagicHash

# useful extensions to know about, but which should be specified on-demand
#
# UndecidableInstances:
#   required for type class wizardry
#   generally only enable if you were expecting to & compilation fails without
# AllowAmbiguousTypes:
#   often goes hand in hand with TypeApplications-heavy code
#   enabling on demand brings attention to the sort of functions to expect
# StarIsType:
#   may need to enable if you're working with old code that uses `Int :: *`

ghc-options:
- -Wall

# `pkg ^>= x.y.z` means `pkg >= x.y.z && < x.(y+1)
dependencies:
- base >= 4.16 && < 4.19
- fortran-src >= 0.14 && < 0.16 # allow 0.14 and 0.15 b/c Nix is stuck on 0.14

- effectful
- effectful-th
- containers

library:
  source-dirs: src
